import { Inter } from "next/font/google";
import "../public/assets/css/animate.css"
import "../public/assets/css/bootstrap.min.css"
import "../public/assets/css/ud-styles.css"
import "../public/assets/css/lineicons.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}